services:
- type: web
  name: CCSUE
  env: python
  repo: https://github.com/gwhsu/Linebot.git
  buildCommand: pip install gunicorn -r requirements.txt
  startCommand: gunicorn app:app
  plan: free
  autoDeploy: false
